### ISSUE TITLE
Nome do repositório e app

### ISSUE THREAD

**Issue by samuel-rosa** [Laboratorio-de-Pedometria/soilDT#2]
@Leticia147, o nome do repositório e do app foram atualizados. Eles se chamam `soilDT`. Verifique se há alguma configuração interna que precise ser atualizada em função dessa alteração.

**Comment by Leticia147** [comment]
Trocar o nome do instalador para soilDT.

**Comment by samuel-rosa** [comment]
`soilDT` vem de _soil decision tree_
