### ISSUE TITLE
Base de dados

### ISSUE THREAD

**Issue by samuel-rosa** [Laboratorio-de-Pedometria/soilDT#5]
Há dois arquivos: `basededados.xlsx` e `basededados2.xlsx`. Os aquivos devem ser nomeados de acordo com o uso. Arquivos redundantes devem ser deletados.

**Comment by Leticia147** [comment]
Existe 2 dois arquivos pois o basededados.xls é referente a base_dados_superficial e basededados2.xls é referente a base_dados_subsuperficial.
Os 2 foram renomeados para nomes mais intuitivos.
